def afficher_menu():
    print("\n========================")
    print("1. Ajouter un dataset")
    print("2. Afficher les datasets")
    print("3. Rechercher un dataset")
    print("4. Trier les datasets")
    print("5. Modifier un dataset")
    print("6. Supprimer un dataset")
    print("7. Statistiques")
    print("8. Sauvegarder (CSV)")
    print("9. Recharger (CSV)")
    print("10. Sauvegarder (JSON)")
    print("11. Recharger (JSON)")
    print("12. Quitter")
    print("========================")